### ISSUE TITLE
CDAR2Parser bug in latest version (3.1.1)

### ISSUE THREAD

**Issue by jkiddo** [oehf/ipf#116]
org.eclipse.emf.ecore.xml.type.impl.XMLTypeDocumentRootImpl cannot be cast to org.openhealthtools.mdht.uml.cda.DocumentRoot
java.lang.ClassCastException: org.eclipse.emf.ecore.xml.type.impl.XMLTypeDocumentRootImpl cannot be cast to org.openhealthtools.mdht.uml.cda.DocumentRoot
	at org.openehealth.ipf.modules.cda.CDAR2Parser.parse(CDAR2Parser.java:61)
	at org.openehealth.ipf.modules.cda.CDAR2Parser.parse(CDAR2Parser.java:43)

**Comment by jkiddo** [comment]
The CDA was the problem
