### ISSUE TITLE
DTM validation too strict for document.creationTime since IPF 3.2

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#151]
Hello IPF Team,

The XDS Toolkit could not send XDS register requests with IPF 3.2.1:

Toolkit is sending:
`<rim:Slot
               name="creationTime">
            <rim:ValueList>
               <rim:Value>20041224</rim:Value>
            </rim:ValueList>
         </rim:Slot>`

Which cause validation error:
`org.openehealth.ipf.commons.ihe.xds.core.validate.XDSMetaDataException: Precision of the timestamp is too low: 20041224
	at org.openehealth.ipf.commons.ihe.xds.core.validate.ValidatorAssertions.metaDataAssert(ValidatorAssertions.java:40) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.TimeValidator.validate(TimeValidator.java:63) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.SlotValueValidation.validate(SlotValueValidation.java:87) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.SlotValueValidation.validate(SlotValueValidation.java:70) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.ObjectContainerValidator.runValidations(ObjectContainerValidator.java:286) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.ObjectContainerValidator.validateFolders(ObjectContainerValidator.java:203) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.ObjectContainerValidator.validate(ObjectContainerValidator.java:193) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
	at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.SubmitObjectsRequestValidator.validate(SubmitObjectsRequestValidator.java:42) ~[ipf-commons-ihe-xds-3.2.1.jar:?]
`

It looks like a side affect from implementation done for "CP-ITI-949: check Folder.lastUpdateTime precision"? The DTM date for creationTime (and also serviceStart and serviceStop) was not restricted by the change proposal.

Thanks,
Thomas

**Comment by unixoid** [comment]
Any chance you could provide the message you send and/or a unit test?

**Comment by Thopap** [comment]
I will try to redo the test tomorrow. But you could already have a look at some testadata which contain just "date" precision for creationTime:
https://github.com/usnistgov/iheos-toolkit2/blob/master/testkit/src/main/resources/testdata/12344/single_doc.xml

**Comment by unixoid** [comment]
This is an ITI-14 XDS.a request message -- are you sure you want to process it?

**Comment by unixoid** [comment]
And the IPF validator finds only one error in this message: wrong format of the patient ID (missing assigning authority).

**Comment by Thopap** [comment]
Sorry my fault, it was a folder lastUpdateTime in the XDS tools test which is not correct. i will submit a issue to update the test in the xds tools.

**Comment by Thopap** [comment]
https://github.com/usnistgov/iheos-toolkit2/issues/264
