### ISSUE TITLE
Update to HAPI FHIR 3.5.0

### ISSUE THREAD

**Issue by ohr** [oehf/ipf#212]
Due to changes in the validation process, this requires dependency on R4 structures

**Comment by ohr** [comment]
for the time being, mode-based validation fails with
{code}
java.lang.ClassCastException: org.hl7.fhir.r4.model.CanonicalType cannot be cast to org.hl7.fhir.r4.model.Reference
	at org.hl7.fhir.r4.validation.InstanceValidator.checkPrimitiveBinding(InstanceValidator.java:1520) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.checkPrimitive(InstanceValidator.java:1428) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3440) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3514) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validateElement(InstanceValidator.java:3524) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.start(InstanceValidator.java:2499) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validateResource(InstanceValidator.java:3697) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validate(InstanceValidator.java:588) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validate(InstanceValidator.java:515) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.r4.validation.InstanceValidator.validate(InstanceValidator.java:499) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator.validate(FhirInstanceValidator.java:232) ~[hapi-fhir-validation-3.4.0.jar:?]
	at org.hl7.fhir.dstu3.hapi.validation.FhirInstanceValidator.validate(FhirInstanceValidator.java:267) ~[hapi-fhir-validation-3.4.0.jar:?]
...
{code}
