### ISSUE TITLE
Investigate problem with embedded tomcat deployment and latest CXF

### ISSUE THREAD

**Issue by stanojevic-boris** [oehf/ipf#27]
Running the IPF-ws-based components (CxfServlet required) deployed in a standalone application with embedded tomcat provides an error:

Caused by: java.lang.NullPointerException
    at org.apache.cxf.transport.servlet.CXFNonSpringServlet.destroy(CXFNonSpringServlet.java:171)
    at org.apache.cxf.transport.servlet.CXFServlet.onApplicationEvent(CXFServlet.java:175)
    at org.apache.cxf.transport.servlet.CXFServlet.onApplicationEvent(CXFServlet.java:43)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:97)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:327)
    at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:941)
    at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:475)
    at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:103)
    at org.springframework.test.context.support.AbstractGenericContextLoader.loadContext(AbstractGenericContextLoader.java:1)
    at org.springframework.test.context.support.DelegatingSmartContextLoader.loadContext(DelegatingSmartContextLoader.java:228)
    at org.springframework.test.context.TestContext.loadApplicationContext(TestContext.java:124)
    at org.springframework.test.context.TestContext.getApplicationContext(TestContext.java:148)
    ... 28 more

**Comment by unixoid** [comment]
I worked around this problem by making `CXFServlet#onApplicationEvent()` a no-op, i.e. by using the following class instead of `CXFServlet`:
```
package foo;

import org.apache.cxf.transport.servlet.CXFServlet;
import org.springframework.context.event.ContextRefreshedEvent;

public class MyCxfServlet extends CXFServlet {
    @Override
    public void onApplicationEvent(ContextRefreshedEvent event) {
        // do nothing
    }
}
```

It seems that both Spring and Tomcat try to manage the servlet, and this leads to collisions.

**Comment by stanojevic-boris** [comment]
Closing the issue. Proposed solution can be used as a workaround or even better use ipf-(cxf-based)-spring-boot-starter's to run IPF-based standalone applications with embedded Tomcat.
