### ISSUE TITLE
groovy.lang.MissingPropertyException when converting AuditMessage to AuditEvent

### ISSUE THREAD

**Issue by Ivan1pl** [oehf/ipf#319]
I am trying to convert AuditMessage instance to AuditEvent using AuditRecordTranslator, this is what happens:

```
groovy.lang.MissingPropertyException: No such property: userId for class: org.hl7.fhir.r4.model.AuditEvent$AuditEventAgentComponent
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.unwrap(ScriptBytecodeAdapter.java:65) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.setProperty(ScriptBytecodeAdapter.java:498) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.openehealth.ipf.commons.ihe.fhir.atna.translation.AuditRecordTranslator.participant(AuditRecordTranslator.groovy:86) ~[ipf-commons-ihe-fhir-r4-audit-3.6.5.jar!/:na]
        at org.openehealth.ipf.commons.ihe.fhir.atna.translation.AuditRecordTranslator$participant$6.callStatic(Unknown Source) ~[na:na]
        at org.openehealth.ipf.commons.ihe.fhir.atna.translation.AuditRecordTranslator$_translateToFhir_closure6.doCall(AuditRecordTranslator.groovy:119) ~[ipf-commons-ihe-fhir-r4-audit-3.6.5.jar!/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.8.jar!/:2.5.8]
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:263) ~[groovy-2.5.8.jar!/:2.5.8]
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.8.jar!/:2.5.8]
        at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.8.jar!/:2.5.8]
        at groovy.lang.Closure.call(Closure.java:421) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2330) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2315) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2356) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.dgm$186.invoke(Unknown Source) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite$PojoMetaMethodSiteNoUnwrapNoCoerce.invoke(PojoMetaMethodSite.java:244) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.callsite.PojoMetaMethodSite.call(PojoMetaMethodSite.java:53) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.8.jar!/:2.5.8]
        at org.openehealth.ipf.commons.ihe.fhir.atna.translation.AuditRecordTranslator.translateToFhir(AuditRecordTranslator.groovy:119) ~[ipf-commons-ihe-fhir-r4-audit-3.6.5.jar!/:na]
        at org.openehealth.ipf.commons.ihe.fhir.atna.translation.AuditRecordTranslator$translateToFhir$0.callCurrent(Unknown Source) ~[na:na]
        at org.openehealth.ipf.commons.ihe.fhir.atna.translation.AuditRecordTranslator.translate(AuditRecordTranslator.groovy:111) ~[ipf-commons-ihe-fhir-r4-audit-3.6.5.jar!/:na]

```

My code:
```
        AuditEvent auditEvent = null
        if (auditMessageWrapper.auditMessage != null) {
            auditEvent = new AuditRecordTranslator().translate(auditMessageWrapper.auditMessage)
        }
```

`auditMessageWrapper.auditMessage` is of the correct type `org.openehealth.ipf.commons.audit.model.AuditMessage`

**Comment by unixoid** [comment]
Any chance you could provide us the audit message (XML) you try to convert?

**Comment by Ivan1pl** [comment]
It happens for pretty much every message I'm trying to convert, here's an example:
```
<AuditMessage xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="D:\data\DICOM\security\audit-message.rnc"><EventIdentification EventActionCode="C" EventDateTime="2001-12-17T09:30:47" EventOutcomeIndicator="0"><EventID code="110104" codeSystemName="DCM" displayName="DICOM Instances Transferred" /></EventIdentification><ActiveParticipant UserID="123" AlternativeUserID="AETITLE=AEFOO" UserIsRequestor="false" NetworkAccessPointID="192.168.1.2" NetworkAccessPointTypeCode="2"><RoleIDCode code="110153" codeSystemName="DCM" displayName="Source Role ID "/></ActiveParticipant><ActiveParticipant UserID="67562" AlternativeUserID="AETITLE=AEPACS" UserIsRequestor="false" NetworkAccessPointID="192.168.1.5" NetworkAccessPointTypeCode="2"><RoleIDCode code="110152" codeSystemName="DCM" displayName="Destination Role ID "/></ActiveParticipant><ActiveParticipant UserID="smitty@readingroom.hospital.org" AlternativeUserID="smith@nema" UserName="Dr. Smith" UserIsRequestor="true" NetworkAccessPointID="192.168.1.2" NetworkAccessPointTypeCode="2"><RoleIDCode code="110153" codeSystemName="DCM" displayName="Source Role ID "/></ActiveParticipant><AuditSourceIdentification AuditEnterpriseSiteID="Hospital" AuditSourceID="ReadingRoom"><AuditSourceTypeCode code="1"/></AuditSourceIdentification><ParticipantObjectIdentification ParticipantObjectID="1.2.840.10008.2.3.4.5.6.7.78.8" ParticipantObjectTypeCode="2" ParticipantObjectTypeCodeRole="3" ParticipantObjectDataLifeCycle="1"><ParticipantObjectIDTypeCode code="110180" codeSystemName="DCM" displayName="Study Instance 725 UID"/><ParticipantObjectDescription><MPPS UID="1.2.840.10008.1.2.3.4.5"/><Accession Number="12341234" /><SOPClass UID="1.2.840.10008.5.1.4.1.1.2" NumberOfInstances="1500"/><SOPClass UID="1.2.840.10008.5.1.4.1.1.11.1" NumberOfInstances="3"/></ParticipantObjectDescription></ParticipantObjectIdentification><ParticipantObjectIdentification ParticipantObjectID="ptid12345" ParticipantObjectTypeCode="1" ParticipantObjectTypeCodeRole="1"><ParticipantObjectIDTypeCode code="2" /><ParticipantObjectName>John Doe</ParticipantObjectName></ParticipantObjectIdentification></AuditMessage>
```

Also, I don't have the knowledge to tell if this is the correct solution, but I copied the class `AuditRecordTranslator` and replaced line 86 (`fhir.userId = new Identifier(value: atna.userID)`) with `fhir.who = new Reference(identifier: new Identifier(value: atna.userID))` and I no longer get this error. Property `userId` does not exist in `AuditEvent.AuditEventAgentComponent`.

**Comment by unixoid** [comment]
@Ivan1pl, thank you for the bug report and the solution proposal.
