### ISSUE TITLE
QueryBuilder validation Error

### ISSUE THREAD

**Issue by alhersh** [oehf/ipf#347]
Hello, I am trying to generate the following audit message from the QueryBuilder and then validate it:

```
QueryBuilder queryBuilder = new QueryBuilder(EventOutcomeIndicator.enumForCode(0),
                "Found IDAT of EHR-ID=",
                EventType.of("110112","Query","Query has been made."),
                PurposeOfUse.of("110106","Export",
                        "Audit event: Data has been exported out of the system."));

        queryBuilder.setAuditSource("3");

        queryBuilder.setQueryingParticipant("SenderApplication","B","Sender Facility",
                "ACC1",true);

        queryBuilder.setRespondingParticipant("ReceiverApplication","A","Receiver Facility",
                "ACC2",false);

        queryBuilder.validate();

```

But, I am getting the following error message:
```
Exception in thread "main" java.lang.NullPointerException
	at org.openehealth.ipf.commons.audit.model.AuditMessage.validate(AuditMessage.java:99)
	at org.openehealth.ipf.commons.audit.event.BaseAuditMessageBuilder.validate(BaseAuditMessageBuilder.java:73)
	at org.openehealth.ipf.commons.audit.event.QueryBuilder.validate(QueryBuilder.java:122)
	at org.highmed.dsf.atna.demo.test5(demo.java:132)
	at org.highmed.dsf.atna.demo.main(demo.java:152)
```

If I neglect the validation the following Audit message will be generated:

```
<AuditMessage>
  <EventIdentification EventActionCode="E" EventDateTime="2021-03-02T11:45:38.931337900Z" EventOutcomeIndicator="0">
    <EventID csd-code="110112" codeSystemName="DCM" originalText="Query" />
    <EventTypeCode csd-code="110112" codeSystemName="Query" originalText="Query has been made." />
    <EventOutcomeDescription>Found IDAT of EHR-ID=</EventOutcomeDescription>
    <PurposeOfUse csd-code="110106" codeSystemName="Export" originalText="Audit event: Data has been exported out of the system." />
  </EventIdentification>
  <ActiveParticipant UserID="SenderApplication" AlternativeUserID="B" UserName="Sender Facility" UserIsRequestor="true" NetworkAccessPointID="ACC1" NetworkAccessPointTypeCode="1">
    <RoleIDCode csd-code="110153" codeSystemName="DCM" originalText="Source Role ID" />
  </ActiveParticipant>
  <ActiveParticipant UserID="ReceiverApplication" AlternativeUserID="A" UserName="Receiver Facility" UserIsRequestor="false" NetworkAccessPointID="ACC2" NetworkAccessPointTypeCode="1">
    <RoleIDCode csd-code="110152" codeSystemName="DCM" originalText="Destination Role ID" />
  </ActiveParticipant>
  <AuditSourceIdentification AuditSourceID="3" />
</AuditMessage>
```

What would be the problem in validation such message?

Thank you.

**Comment by ohr** [comment]
It stumbles over the fact that there are no ParticipantObjectIdentification. Clearly a bug. We have null checks in the serializer, but here it was forgotten.

But you should anyway consider to add such a ParticipantObjectIdentification object e.g. to add query details to the audit record.

**Comment by alhersh** [comment]
Many thanks for your fast prompt!
Adding ParticipantObjectIdentification as you have suggested has overcome the validation error.
