### ISSUE TITLE
Missing converter for PDQ continuation protocol

### ISSUE THREAD

**Issue by jkiddo** [oehf/ipf#460]
We're seeing the following error when using the PDQv3 continuation flow:

```
Caused by: org.apache.camel.InvalidPayloadException: No body available of type: net.ihe.gazelle.hl7v3.quqiin000003UV01.QUQIIN000003UV01Type but has type: java.lang.String on: Message. Caused by: No type converter available to convert from type: java.lang.String to the required type: net.ihe.gazelle.hl7v3.quqiin000003UV01.QUQIIN000003UV01Type. Exchange[E39DC8466F4F76B-0000000000000005]. Caused by: [org.apache.camel.NoTypeConversionAvailableException - No type converter available to convert from type: java.lang.String to the required type: net.ihe.gazelle.hl7v3.quqiin000003UV01.QUQIIN000003UV01Type]
	at org.apache.camel.support.MessageSupport.getMandatoryBody(MessageSupport.java:128) ~[camel-support-4.4.2.jar:4.4.2]
	at org.apache.camel.support.builder.ExpressionBuilder$39.evaluate(ExpressionBuilder.java:1385) ~[camel-support-4.4.2.jar:4.4.2]
	... 160 common frames omitted
Caused by: org.apache.camel.NoTypeConversionAvailableException: No type converter available to convert from type: java.lang.String to the required type: net.ihe.gazelle.hl7v3.quqiin000003UV01.QUQIIN000003UV01Type
	at org.apache.camel.impl.converter.CoreTypeConverterRegistry.mandatoryConvertTo(CoreTypeConverterRegistry.java:199) ~[camel-base-4.4.2.jar:4.4.2]
	at org.apache.camel.support.MessageSupport.getMandatoryBody(MessageSupport.java:126) ~[camel-support-4.4.2.jar:4.4.2]
	... 161 common frames omitted
```

Would that be a feature request or is there something we're missing to wire up?

**Comment by jkiddo** [comment]
@unixoid would you know?

**Comment by unixoid** [comment]
Already working on it :)

**Comment by unixoid** [comment]
@jkiddo I revised the Camel converters for HL7v3 messages and added missing ones (actually, for ITI-44 and ITI-46, as well as for continuation/cancel messages of ITI-47).  Additionally, updated sequence diagrams in documentation.
