### ISSUE TITLE
XDS Response Validation fails if response contain On Demand Documents

### ISSUE THREAD

**Issue by Thopap** [oehf/ipf#92]
If a ITI-18 StoredQuery Response contain On Demand Documents, the IPF response validation throw the following validation error:

`org.openehealth.ipf.commons.ihe.xds.core.validate.XDSMetaDataException: Slot contains incorrect amount of values. Slot = hash, allowed = [ 1-  1], Was =    0
        at org.openehealth.ipf.commons.ihe.xds.core.validate.ValidatorAssertions.metaDataAssert(ValidatorAssertions.java:40)
        at org.openehealth.ipf.commons.ihe.xds.core.validate.SlotValueValidation.validate(SlotValueValidation.java:82)
        at org.openehealth.ipf.commons.ihe.xds.core.validate.SlotValueValidation.validate(SlotValueValidation.java:70)
        at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.ObjectContainerValidator.runValidations(ObjectContainerValidator.java:243)
        at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.ObjectContainerValidator.validateDocumentEntries(ObjectContainerValidator.java:209)
        at org.openehealth.ipf.commons.ihe.xds.core.validate.requests.ObjectContainerValidator.validate(ObjectContainerValidator.java:154)
        at org.openehealth.ipf.commons.ihe.xds.core.validate.responses.QueryResponseValidator.validate(QueryResponseValidator.java:49)
        at org.openehealth.ipf.platform.camel.ihe.xds.XdsCamelValidators$2.process(XdsCamelValidators.java:65) `

But since On Demand Documents do not have `Hash` or `Size`, the validation of these slots must be ommited.
Issue was seen in IPF 3.0.4.

**Comment by Thopap** [comment]
Thank you for this quick fix. Could you merge the fix to 3.0-branch?

**Comment by unixoid** [comment]
Done.
